### ISSUE TITLE
update entity-search-webapp to 2.7.0

### ISSUE THREAD

**Issue by arawinters** [Senzing/senzinggo#36]
The version of the webapp needs to be updated. see release notes: https://github.com/Senzing/entity-search-web-app/releases/tag/2.7.0

**Comment by antaenc** [comment]
SenzingGo pulls the latest images from a list we publish on Git, if this list isn't up to date yet it won't pull latest version. It's also possible to override the version pulled if you require a specific version/tag. The current list and tags can be seen with SenzingGo.py -il (--imagesList).
